"use client"

// ShaderBackground — generated by the 21st.dev Shader Builder
// Adapted for ARC.BD Dark/Black Theme. Zero dependencies: one WebGL canvas that fills its parent.
// Drop it behind your content with <div className="relative"><ShaderBackground className="absolute inset-0" />…

import { useEffect, useRef, useState } from "react"

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`

const FRAG = `#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, warp
uniform vec4 u_surface;    // detail, contrast, brightness, saturation
uniform vec4 u_finish;     // hue, vignette, blur, grain
uniform vec4 u_transform;  // seed, rotation, drift, OKLab toggle
uniform vec4 u_space;      // offset.xy, pointer.xy
uniform vec4 u_cursor;

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_rotate u_transform.y

// High-fidelity 3D multi-layered liquid silk ribbon field
float getSilkHeight(vec2 p, float t) {
  vec2 q = p * 1.55;
  
  // Layer 1: Primary sweeping liquid folds
  q.x += 0.52 * sin(1.2 * q.y + t * 0.38 + 0.7);
  q.y += 0.52 * cos(1.1 * q.x + t * 0.32 + 1.2);
  
  // Layer 2: Secondary silky undulations
  q.x += 0.34 * sin(2.3 * q.y - t * 0.44 + 2.1);
  q.y += 0.34 * cos(1.9 * q.x + t * 0.39 + 0.9);
  
  // Layer 3: Fine liquid satin ripples
  q.x += 0.18 * sin(3.6 * q.y + t * 0.52 + 3.4);
  q.y += 0.18 * cos(3.1 * q.x - t * 0.46 + 2.4);
  
  // Layer 4: Micro specular ribbon ridges
  q.x += 0.09 * sin(5.2 * q.y - t * 0.60 + 1.5);
  q.y += 0.09 * cos(4.7 * q.x + t * 0.55 + 3.8);
  
  float val = 0.5 + 0.5 * sin(q.x * 1.2 + q.y * 1.4);
  return val;
}

// True 3D Shading Engine: Surface Normals, Diffuse Curvature, Specular Glints & Fresnel Sheen
vec3 shade(vec2 p, float t) {
  float eps = 0.003;
  float h = getSilkHeight(p, t);
  float hx = getSilkHeight(p + vec2(eps, 0.0), t);
  float hy = getSilkHeight(p + vec2(0.0, eps), t);
  
  // 3D surface normal derived from continuous slope
  vec3 normal = normalize(vec3((h - hx) / eps * 0.22, (h - hy) / eps * 0.22, 1.0));
  
  // 3D Directional Key Light from top-left
  vec3 lightDir = normalize(vec3(0.60, 0.75, 0.85));
  vec3 viewDir = vec3(0.0, 0.0, 1.0);
  vec3 halfVec = normalize(lightDir + viewDir);
  
  // 3D Diffuse curvature
  float diff = max(0.0, dot(normal, lightDir));
  
  // Dual-lobe high-gloss specular highlight (soft satin glow + pinpoint chrome glint)
  float spec1 = pow(max(0.0, dot(normal, halfVec)), 18.0);
  float spec2 = pow(max(0.0, dot(normal, halfVec)), 48.0);
  
  // 3D Fresnel rim light (creates dimensional silk ribbon contours)
  float fresnel = pow(1.0 - max(0.0, dot(normal, viewDir)), 2.6);
  
  // Base body color mapped smoothly from height
  float val = smoothstep(0.04, 0.96, h);
  float n = max(u_colorCount - 1.0, 1.0);
  float f = clamp(val, 0.0, 1.0) * n;
  
  vec3 baseCol = u_colors[0];
  for (int i = 0; i < 7; i++) {
    if (float(i) < n) {
      float w = smoothstep(0.0, 1.0, clamp(f - float(i), 0.0, 1.0));
      baseCol = mix(baseCol, u_colors[i + 1], w);
    }
  }
  
  // Combine 3D diffuse body with ambient
  vec3 col = baseCol * (0.55 + 0.65 * diff);
  
  // Glossy liquid chrome specular crest + silk fold rim light + chrome glint
  vec3 glossColor = vec3(0.55, 0.65, 0.85);
  vec3 glintColor = vec3(0.85, 0.92, 1.00);
  col += glossColor * (spec1 * 0.85 + fresnel * 0.35);
  col += glintColor * (spec2 * 0.75);
  
  return col;
}

void main() {
  vec2 uv = gl_FragCoord.xy / u_resolution.xy;
  
  // Responsive coordinate space centered for both portrait mobile and landscape desktop
  float minDim = min(u_resolution.x, u_resolution.y);
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / minDim;
  
  if (u_resolution.x < u_resolution.y) {
    p *= 0.82;
    p.y -= 0.10;
  }
  
  p *= u_scale;
  if (abs(u_rotate) > 0.0001) {
    float cr = cos(u_rotate), sr = sin(u_rotate);
    p = mat2(cr, -sr, sr, cr) * p;
  }
  p += u_space.xy;
  
  vec3 col = shade(p, u_time);
  
  // Smooth subtle perimeter fade to blend seamlessly into background without eating into content
  vec2 radialUv = (uv - 0.5) * vec2(1.0, u_resolution.y / max(u_resolution.x, 1.0) * 0.75);
  float dist = length(radialUv);
  float radialFade = smoothstep(0.48, 0.92, dist);
  col = mix(col, u_colors[0], radialFade);
  
  // Smooth vertical bottom blend to merge into next section seamlessly
  float bottomFade = smoothstep(0.0, 0.22, uv.y);
  col = mix(u_colors[0], col, bottomFade);
  
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`

// Smooth luminous 3D obsidian black palette (perfectly calibrated with #09090b)
const UNIFORMS = {
  colors: [
    [0.0353, 0.0353, 0.0431], // #09090b site background base void
    [0.0588, 0.0667, 0.0902], // Deep midnight shadow
    [0.1098, 0.1294, 0.1843], // 3D dark slate body
    [0.2118, 0.2549, 0.3647], // Rich liquid silk midtone
    [0.3804, 0.4471, 0.6196], // Specular gloss ribbon ridge
    [0.6275, 0.7059, 0.9020], // Soft luminous silver crest peak
    [0.6275, 0.7059, 0.9020],
    [0.6275, 0.7059, 0.9020],
  ] as [number, number, number][],
  colorCount: 6,
  scale: 0.580,
  intensity: 0.350,
  paramA: 0.500,
  warp: 0.000,
  detail: 1.000,
  contrast: 1.000,
  brightness: 0.000,
  saturation: 0.250,
  hue: 0.0000,
  vignette: 0.200,
  blur: 0.0000,
  grain: 0.000,
  seed: 520.0,
  rotate: 0.850,
  offsetX: 0.000,
  offsetY: 0.050,
  drift: 0.000,
  cursorEnabled: false,
  cursorEffect: 2.0,
  cursorStrength: 0.650,
  cursorRadius: 0.460,
  oklab: 1.0,
  timeOffset: 2.400,
  timeScale: 0.180,
}

const pendingContextReleases = new WeakMap<HTMLCanvasElement, number>()

export function ShaderBackground({ className }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [isReady, setIsReady] = useState(false)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const pendingRelease = pendingContextReleases.get(canvas)
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease)
    pendingContextReleases.delete(canvas)
    const gl = canvas.getContext("webgl", {
      antialias: false,
      alpha: false,
      depth: false,
      stencil: false,
      preserveDrawingBuffer: false,
      powerPreference: "low-power",
    })
    if (!gl) return

    const compile = (type: number, src: string) => {
      const s = gl.createShader(type)!
      gl.shaderSource(s, src)
      gl.compileShader(s)
      return s
    }
    const program = gl.createProgram()!
    const vertexShader = compile(gl.VERTEX_SHADER, VERT)
    const fragmentShader = compile(gl.FRAGMENT_SHADER, FRAG)
    gl.attachShader(program, vertexShader)
    gl.attachShader(program, fragmentShader)
    gl.linkProgram(program)
    gl.deleteShader(vertexShader)
    gl.deleteShader(fragmentShader)
    gl.useProgram(program)

    const buf = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buf)
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 3, -1, -1, 3]),
      gl.STATIC_DRAW,
    )
    const loc = gl.getAttribLocation(program, "a_position")
    gl.enableVertexAttribArray(loc)
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0)

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
      space: gl.getUniformLocation(program, "u_space"),
      cursor: gl.getUniformLocation(program, "u_cursor"),
    }
    gl.uniform3fv(uni.colors, new Float32Array(UNIFORMS.colors.flat()))
    gl.uniform4f(
      uni.shape,
      UNIFORMS.scale,
      UNIFORMS.intensity,
      UNIFORMS.paramA,
      UNIFORMS.warp,
    )
    gl.uniform4f(
      uni.surface,
      UNIFORMS.detail,
      UNIFORMS.contrast,
      UNIFORMS.brightness,
      UNIFORMS.saturation,
    )
    gl.uniform4f(
      uni.finish,
      UNIFORMS.hue,
      UNIFORMS.vignette,
      UNIFORMS.blur,
      UNIFORMS.grain,
    )
    gl.uniform4f(
      uni.transform,
      UNIFORMS.seed,
      UNIFORMS.rotate,
      UNIFORMS.drift,
      UNIFORMS.oklab,
    )
    gl.uniform4f(
      uni.cursor,
      0,
      UNIFORMS.cursorEffect,
      UNIFORMS.cursorStrength,
      UNIFORMS.cursorRadius,
    )

    let targetX = 0
    let targetY = 0
    let targetPresence = 0
    let mouseX = 0
    let mouseY = 0
    let cursorPresence = 0
    let pointerKnown = false
    let pointerClientX = 0
    let pointerClientY = 0
    let bounds = canvas.getBoundingClientRect()
    let raf = 0
    let lastNow: number | null = null
    let lastFrameTime = 0
    let visible = document.visibilityState === "visible"
    let inView = true
    let disposed = false
    const start = performance.now()
    const timeAnimated = Math.abs(UNIFORMS.timeScale) > 0.0001

    const resizeCanvas = () => {
      bounds = canvas.getBoundingClientRect()
      if (bounds.width === 0 || bounds.height === 0) return
      const dpr = Math.min(window.devicePixelRatio || 1, 1.25)
      const rawWidth = Math.max(1, Math.round(bounds.width * dpr))
      const rawHeight = Math.max(1, Math.round(bounds.height * dpr))
      const pixelScale = Math.min(
        1,
        Math.sqrt(420_000 / Math.max(1, rawWidth * rawHeight)),
      )
      const width = Math.max(1, Math.round(rawWidth * pixelScale))
      const height = Math.max(1, Math.round(rawHeight * pixelScale))
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width
        canvas.height = height
        gl.viewport(0, 0, width, height)
      }
    }

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) {
        raf = requestAnimationFrame(render)
      }
    }

    const updatePointerTarget = () => {
      if (!pointerKnown) return
      if (bounds.width === 0 || bounds.height === 0) return
      const inside =
        pointerClientX >= bounds.left &&
        pointerClientX <= bounds.right &&
        pointerClientY >= bounds.top &&
        pointerClientY <= bounds.bottom
      if (!inside) {
        targetPresence = 0
        requestRender()
        return
      }
      const nextX = ((pointerClientX - bounds.left) / bounds.width) * 2 - 1
      const nextY = -(((pointerClientY - bounds.top) / bounds.height) * 2 - 1)
      if (targetPresence === 0 && cursorPresence < 0.01) {
        mouseX = nextX
        mouseY = nextY
      }
      targetX = nextX
      targetY = nextY
      targetPresence = 1
      requestRender()
    }
    const onPointerMove = (event: PointerEvent) => {
      pointerKnown = true
      pointerClientX = event.clientX
      pointerClientY = event.clientY
      bounds = canvas.getBoundingClientRect()
      updatePointerTarget()
    }
    const onPointerLeave = () => {
      pointerKnown = false
      targetPresence = 0
      requestRender()
    }
    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect()
      resizeCanvas()
      updatePointerTarget()
      requestRender()
    }
    window.addEventListener("resize", updateLayout, { passive: true })
    if (UNIFORMS.cursorEnabled) {
      window.addEventListener("pointermove", onPointerMove, { passive: true })
      window.addEventListener("pointercancel", onPointerLeave)
      window.addEventListener("scroll", updateLayout, { passive: true })
      window.addEventListener("blur", onPointerLeave)
      document.documentElement.addEventListener("pointerleave", onPointerLeave)
    }

    const resizeObserver = new ResizeObserver(updateLayout)
    resizeObserver.observe(canvas)
    const intersectionObserver = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true
      if (inView) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    })
    intersectionObserver.observe(canvas)
    const onVisibilityChange = () => {
      visible = document.visibilityState === "visible"
      if (visible) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    }
    document.addEventListener("visibilitychange", onVisibilityChange)

    updateLayout()

    function render(now: number) {
      raf = 0
      if (disposed || !visible || !inView || !canvas || !gl) return

      // Smooth frame-rate regulator: caps render at ~45fps to save 50% CPU/GPU overhead on all devices
      if (lastFrameTime !== 0 && now - lastFrameTime < 22) {
        requestRender()
        return
      }
      lastFrameTime = now

      const dt = lastNow === null ? 0 : Math.min((now - lastNow) / 1000, 0.1)
      lastNow = now
      const follow = 1 - Math.exp(-12 * dt)
      mouseX += (targetX - mouseX) * follow
      mouseY += (targetY - mouseY) * follow
      cursorPresence += (targetPresence - cursorPresence) * follow
      const width = canvas.width
      const height = canvas.height
      gl.uniform4f(
        uni.scene,
        width,
        height,
        UNIFORMS.timeOffset + Math.sin(((now - start) / 1000) * UNIFORMS.timeScale) * 0.4,
        UNIFORMS.colorCount,
      )
      gl.uniform4f(
        uni.space,
        UNIFORMS.offsetX,
        UNIFORMS.offsetY,
        mouseX,
        mouseY,
      )
      gl.uniform4f(
        uni.cursor,
        UNIFORMS.cursorEnabled ? cursorPresence : 0,
        UNIFORMS.cursorEffect,
        UNIFORMS.cursorStrength,
        UNIFORMS.cursorRadius,
      )
      gl.drawArrays(gl.TRIANGLES, 0, 3)
      const pointerSettling =
        Math.abs(targetX - mouseX) > 0.001 ||
        Math.abs(targetY - mouseY) > 0.001 ||
        Math.abs(targetPresence - cursorPresence) > 0.001
      if (timeAnimated || pointerSettling) requestRender()
      else lastNow = null
    }
    render(performance.now())
    setIsReady(true)
    requestRender()
    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      resizeObserver.disconnect()
      intersectionObserver.disconnect()
      document.removeEventListener("visibilitychange", onVisibilityChange)
      window.removeEventListener("resize", updateLayout)
      if (UNIFORMS.cursorEnabled) {
        window.removeEventListener("pointermove", onPointerMove)
        window.removeEventListener("pointercancel", onPointerLeave)
        window.removeEventListener("scroll", updateLayout)
        window.removeEventListener("blur", onPointerLeave)
        document.documentElement.removeEventListener(
          "pointerleave",
          onPointerLeave,
        )
      }
      gl.deleteBuffer(buf)
      gl.deleteProgram(program)
      const releaseTimer = window.setTimeout(() => {
        if (pendingContextReleases.get(canvas) !== releaseTimer) return
        pendingContextReleases.delete(canvas)
        gl.getExtension("WEBGL_lose_context")?.loseContext()
        canvas.width = 1
        canvas.height = 1
      }, 0)
      pendingContextReleases.set(canvas, releaseTimer)
    }
  }, [])

  return (
    <canvas
      ref={canvasRef}
      className={`${className || ""} transition-opacity duration-300 ease-out ${isReady ? "opacity-100" : "opacity-0"}`}
      style={{
        display: "block",
        width: "100%",
        height: "100%",
        transform: "translateZ(0)",
        willChange: "transform",
      }}
    />
  )
}
